In [1]:
import numpy as np

In [6]:
a = np.random.random((20))
a

array([0.9578651 , 0.76034815, 0.38645102, 0.52341329, 0.66851259,
       0.02415224, 0.41414107, 0.47089224, 0.96678956, 0.36168529,
       0.38194512, 0.26564383, 0.67672562, 0.61781231, 0.64525082,
       0.91110036, 0.15732182, 0.08603116, 0.45387638, 0.01844465])

In [7]:
np.exp(a)

array([2.6061267 , 2.1390208 , 1.47174831, 1.68777871, 1.95133274,
       1.02444627, 1.51307057, 1.6014224 , 2.62948909, 1.43574703,
       1.46513167, 1.30427044, 1.96742507, 1.85486573, 1.90646515,
       2.48705769, 1.17037221, 1.08984029, 1.57440335, 1.0186158 ])

In [9]:
1 + a

array([1.9578651 , 1.76034815, 1.38645102, 1.52341329, 1.66851259,
       1.02415224, 1.41414107, 1.47089224, 1.96678956, 1.36168529,
       1.38194512, 1.26564383, 1.67672562, 1.61781231, 1.64525082,
       1.91110036, 1.15732182, 1.08603116, 1.45387638, 1.01844465])

In [10]:
a = [ i for i in range(30) ]

In [14]:
a = [ i / max(a) for i in a ]

In [16]:
a = [ 1, 2, 3, 4, 5 ]
b = [ 2, 2, 2, 2, 2 ]
c = [ 4, 4, 4, 4, 4 ]

In [17]:
c  / b

TypeError: unsupported operand type(s) for /: 'list' and 'list'